// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyugbumbhiwpkybxrgjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5dWdidW1iaGl3cGt5YnhyZ2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODU5MzYsImV4cCI6MjA2NTU2MTkzNn0.ljnsHG0LbJSCFB7DnGbmls8tYnpU5BzCl6zJJ16bmCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);